### ISSUE TITLE
Temp Resource Group

### ISSUE THREAD

**Issue by dstarr** [Azure/Commercial-Marketplace-SaaS-Accelerator#119]
**Describe the solution you'd like**
Allow optional parameter for temp resource group

**Additional context**
May allow me to stop a collision with an existing resource group.

**Comment by alexdrenea** [comment]
Could we do without the temp storage account in the first place?
I have a working update of the deploy script and ARM template that does not require the temp RG. The storage account is created in the main RG and only holds the bacpac, and can be used later for enabling logs or other features. Since it doesn't cost anything I see no issue leaving it deployed in the RG. 

Additionally, the deploy script is rewritten to use AZ CLI instead of AzureRM and adds KeyVault integration to the entire solution. If there is interest, I can quickly make a PR for it.

@dstarr @code4clouds
