### ISSUE TITLE
Admin Page: Add programmable webhook trigger custom actions

### ISSUE THREAD

**Issue by code4clouds** [Azure/Commercial-Marketplace-SaaS-Accelerator#134]
**Is your feature request related to a problem? Please describe.**
Allow the Administrator to program of custom actions for different actions

**Describe the solution you'd like**
Allow the Administrator to program of custom actions for different actions

**Describe alternatives you've considered**
In the plans menu allow custom actions that emit webhooks

**Additional context**

**Comment by dstarr** [comment]
Will be taken care of in auto-provisioning work.

**Comment by santhoshb-msft** [comment]
Currently keep this as enhancement but maybe need to bring other issues #274 and #251 asks clarity in here too.

**Comment by code4clouds** [comment]
Maybe for 6.1? 7?

**Comment by clementchane** [comment]
Hello,
I just installed the saas accelerator for my app (v7)
I want the customer to have his information sent to my own webhook when he subscribes, so that I can automatically create his account in my application, and be activated automatically. 
Is that what is asked or is that already possible (because it looks like a basic use case) ?

Thanks for your help!
