### ISSUE TITLE
How do publisher test the SaaS offering with custom landing page and webhooks ?

### ISSUE THREAD

**Issue by ameyasubhedar** [Azure/Commercial-Marketplace-SaaS-Accelerator#200]
The SaaS accelerator is not providing any way for publishers to test custom setup with custom deployment, landing pages, and webhooks! This seems a bit strange to me!

How do a publisher test and verify the offer with sample or test `x-ms-marketplace-token`. I don't want to publish an offer and then test it out.

You should provide public endpoints with some sample subscription data and a REST API to generate test x-ms-marketplace-token so that the publishers can have their SaaS offering thoroughly tested.

**Comment by ameyasubhedar** [comment]
An example is Stripe Payment API. I can issue webbooks with sample data to try and test out payment integration before publishing. It can be simple setup with predefined data at a minimal and endpoints to access the test data.

**Comment by code4clouds** [comment]
The SaaS Accelerator provides publishers a way to complete the Marketplace requirements.  In order to test the SaaS Accelerator, you need an account in Partner Center and fill in the technical configuration.  Once the offer is published use the Preview Audience and the Preview link to test the workflow as a customer before going live.
