### ISSUE TITLE
Add integration webhook to add the custom logic during subscription activation

### ISSUE THREAD

**Issue by santhoshb-msft** [Azure/Commercial-Marketplace-SaaS-Accelerator#274]
**Is your feature request related to a problem? Please describe.**
Add integration webhook to add the custom logic during subscription activation

**Describe the solution you'd like**
Add integration webhook to add the custom logic during subscription activation

**Describe alternatives you've considered**
Add integration webhook to add the custom logic during subscription activation

**Additional context**

**Comment by s8mathur** [comment]
As an ISV, I need the hooks to write to automatically provision users/subscription/quotas, etc in my SaaS. The hooks must pass on subscription data (context) and web-form metadata (if collected) to the listener. Ditto for end-state hooks of the user/subscription lifecycle. 
![fullfillment-automation](https://user-images.githubusercontent.com/5669765/178435897-aa7ad45e-caf9-46e6-9da6-6253bf87cae2.png)

**Comment by alexdrenea** [comment]
I've been thinking about this a lot. 
Today, there is the ability to custom code your logic in the accelerator (there are some hooks where you can tie in your code) and redeploy the accelerator. 
However, that does not really work well with the "no-code" approach that we took with the deployment steps (where the partner deploys the code without establishing a real CI/CD pipelines and just deploy a point-in-time version of the accelerator).

As a potential solution or feature-add, I like the approach the MONA accelerator took, that is, deploy a blank Logic App, and tie it to the webhook controllers, so that the partners can have a no-code / no-redeployment option in case they need to trigger any extra functionality from the webhooks.

**Comment by dstarr** [comment]
I have a proposal on how to implement this feature we can discuss. Have already vetted it with Julio, Santhosh, and Patrick.

**Comment by santhoshb-msft** [comment]
As the other one is marked as duplicate, removing the duplicate tag on this.

**Comment by s8mathur** [comment]
Hi @dstarr and @santhoshb-msft ; any update on this please? 
This is rather important, to put it politely. Many B2B SaaS these days is DIY/self-serve, so only focusing on sales person assisted/high-touch onboarding and fullfilment isn't desirable.

**Comment by santhoshb-msft** [comment]
Design:

Phase-1
- Send a copy a of webhook payload to an endpoint.
- A setting in the config to provide an endpoint URL
- Fire and forget and log the response (if any).
- Add the subscription info

Phase-2
- Retry at multiple scenarios (re-try 3times, ability to retry each failed webhook from the UI)
-

**Comment by santhoshb-msft** [comment]
prelim discussion on the json structure

<eventType> : [LandingPage, ChangePlan, ChangeQuantity, Renew, Unsubscribe, Suspend, Reninstate]

{
    "custominfo": {
        "applicationName": "<fromtheDB>",
        "eventType": "<eventType>",
        "landingpageFields" : {
            "" :"",
            "" :"",
            "" :"",
            "" :""
        } [optional, fields from the db]
    },
    "EventPayloadFromMarketplace": "{
        [<evenType> Payload] [response from the marketplace client lib result]
    }
}
