### ISSUE TITLE
Not getting email for Pending Activation activity and Subscribed activity

### ISSUE THREAD

**Issue by gjain-sag** [Azure/Commercial-Marketplace-SaaS-Accelerator#482]
**Describe the bug**
I am using Commercial-Marketplace-Saas-Accelerator 7.0.0.
I am not getting any email for Pending Activation and Subscribed activities. I checked application logs but didn't found any logging for email failures error in logs.

I have configured the Email settings in Settings menu as well as RecipientEmail's in template. Not sure what else is missing

**To Reproduce**
1. Install Commercial Marketplace-Saas-Accelerator 7.0.0
2. Setup partner center with Landing page and webhook url
3. Initiate an subscription workflow 
4. Once on landing page click subscribe.

**Expected behavior**
Email should be received based on configuration 

**Screenshots**
![image](https://user-images.githubusercontent.com/75057599/234298278-b88b0698-a9c6-4b25-b853-0918399a7bc5.png)
![image](https://user-images.githubusercontent.com/75057599/234299025-3e38e70d-8da1-4b56-a03c-679b19f2a87f.png)

Is there a way we can troubleshoot this error to find the root cause?

**Comment by santhoshb-msft** [comment]
Hi @gjain-sag , we will add additional logging for email sending case. But can see any log on your SMTP end? like if you received any email to be sent?

**Comment by worph** [comment]
Also having the same issue using sendgrid I tested port 587 and 465:
![image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/10581933/7b1ead8a-56cb-47c8-a72b-b09b5c943a6f)

A "send test mail button" could be a plus to test this configuration because doing subscribe ans unsubscribe is not very efficient to test mail.

**Comment by damian-t** [comment]
Having the same issue with an Office365 email account. SMTP auth is enabled on the sender mailbox
<img width="1166" alt="Screenshot 2023-05-19 at 14 20 25" src="https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/42738586/0a992e16-d962-4916-9e9c-29e8c1701754">

**Comment by quartilesoftware** [comment]
I also have the same issue, using SendGrid.

Nothing in the SendGrid logs shows an attempt was even made to reach their service.

I'm using a working SendGrid verified sender as the email address in SaaS Accelerator

**Comment by quartilesoftware** [comment]
For anyone else who stumbles across this, watch this for what may be your missing piece:

https://www.youtube.com/watch?v=IniPruOrV8I  start at 4:30 of 8:47 minutes.

It's not immediately obvious from the documentation that as well as setting up  SMTP configuration in application config, and as well as enabling the three "IsEmailEnabled" settings, you then *_also_* have to:

go into each plan
click the "Events" tab
then for each of the activate/unsubscribe/cancel options, also enable that, for every plan

The entire documentation set could be usefully refined into a single, definitive and comprehensive source, instead of having a plethora of slide decks, GitHub instructions, labs, videos, workshop transcripts, at several diffferent locations, all in various stages of being slightly - but crucially - out of date.

**Comment by santhoshb-msft** [comment]
Thank you for the feedback @quartilesoftware, We will review this internally. 
I'm glad the issue was resolved. closing this for now.

cc: @dstarr
