### ISSUE TITLE
Fresh installation gives OOPS Error 500: Keyword not supported

### ISSUE THREAD

**Issue by CarlosGamez-Nova** [Azure/Commercial-Marketplace-SaaS-Accelerator#508]
**Describe the bug**
A fresh new installation of this app presents error on the landing and administration pages

**To Reproduce**
1. Install new SaaS-Accelerator application as per instructions
2. Navitage to the Landing page

**Expected behavior**
To present user with landing page

**Screenshots**

![image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/118949383/458cdb39-5db2-4e4a-bc87-559a4ab30f72)

**Environment (please complete the following information):**
 - Are you using the CloudShell - Yes

**Comment by santhoshb-msft** [comment]
@CarlosGamez-Nova please re run with the latest install instructions(https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/docs/Installation-Instructions.md#basic-installation-script). We have not seen this happen. any further information might help us to analyze further.

**Comment by ekersale** [comment]
Hi, we have the same issue following that exact same documentation.
![image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/7691499/f3c5cf51-1e32-4e10-bf99-c3b8086d4d63)

**Comment by santhoshb-msft** [comment]
@ekersale Can you please check the configuration of the app services and check to see what is the keyvault references looking like?

**Comment by ekersale** [comment]
Ok so i think i found the issue. If there was an issue during the first deployment, and you rerun it for a second time, you have to ensure to purge manually the keyvault as it stay unpurged and block further recreation.

**Comment by santhoshbomma9** [comment]
That's right, I am glad you found the issue. @ekersale 

@CarlosGamez-Nova please let me know if you were able to fix your issue as well. As I mentioned, app service config is better place to start troubleshooting.

**Comment by CarlosGamez-Nova** [comment]
Hi,
Thank you for looking into this issue. @ekersale is correct. That's exactly what was causing the issue. I went through a manual purging of the keyvalut and reinstalled. Everything worked correctly after that.
Thanks again

**Comment by santhoshb-msft** [comment]
Thank you for the confirmation @CarlosGamez-Nova. Closing this for now as a known limitation that we need to manually purge the key vault before running the script.

**Comment by dwiesttq** [comment]
I just encountered this issue, but the configured key vault was active.  Both the portal and admin app services had the correct values listed for the SaaSApiConfiguration__ClientSecret environment variable and the DefaultConnection connection string.  There was a green checkmark next to the settings in the admin app service, but a red checkmark in the portal app service.  Clicking the "Pull reference values" button resolved the issue.

I did have a failed deployment the first time I ran Deploy.ps1 due to me not being aware that a deleted key vault may still need to be purged (I had previously subscribed to the Marketplace offer for the SaaS Accelerator before using this repository).  I used a different value for the WebAppNamePrefix parameter during my second deployment, but I did run the script in the same PowerShell cloud console.

It would be helpful if the deployment script either checked that the specified WebAppNamePrefix doesn't collide with an existing key vault or if the script generated a unique name, extension, etc.  In any case, this project was extremely helpful for quickly getting a Marketplace offer up and running!
